### ISSUE TITLE
Support NetStandard 2.0

### ISSUE THREAD

**Issue by jpenniman** [nhibernate/NHibernate.Mapping.Attributes#11]
It's very exiting to see significant progress being made on porting NHibernate core to NetStandard 2.0!  Is there something in the works to also port NHibernate.Mapping.Attributes? We use this library in all our NHibernate based projects.

@fredericDelaporte, is this something you're targeting in the 5.0 release?

If someone isn't already taking up the task, I'm more than happy to take this on.

**Comment by fredericDelaporte** [comment]
NHibernate 5.0 is released and does not support NetStandard. So NHibernate.Mapping.Attributes will not either. This will wait some future version.

**Comment by jpenniman** [comment]
Yes, but NHibernate 5.0 was retargeted to Net461, so there's no reason NHibernate.Mapping.Attributes couldn't go to NetStandard now (IESI Collections, for example, is already NetStandard).

I was just curious if it was on the roadmap and offering my services in doing the port. It's something we'll be doing anyway as we test the NHibernate NetStandard conversion.  If you're going to release a NetStandard version in lock-step with the NHibernate NetStandard release, I won't worry about it.

**Comment by fredericDelaporte** [comment]
Iesi is NetStandard because it has no dependencies on NHibernate (that is the other way round, NHibernate depending on it). And since it will need to be NetStandard for the ongoing work on NHibernate, it has been done.

While technically NHibernate.Mapping.Attributes has no dependency on NHibernate, it is meant to be used with NHibernate, so I do not see much advantages in already adapting it to NetStandard.
It could be for having that already done, but that will not be done by me, I am focusing on other things currently.

Of course if you want to do it, you are welcome to submit a PR.

**Comment by jpenniman** [comment]
Is this something on the roadmap now that NHibernate targets Netstandard2.0? If you don't have the bandwidth, I'll take a stab at it.

**Comment by fredericDelaporte** [comment]
Contribution welcome. Personally, I am not working on attributes, I am currently working on providing some .Net Core NHibernate.Caches.

**Comment by jpenniman** [comment]
Ok. I'll do the re-target and submit a PR.

**Comment by MSWCRB** [comment]
Lacking .NET Standard support is a breaking problem for those of us that use NHibernate Attributes in classes of Models we include in NuGet packages for redistribution.  It is understood that NHibernate doesn't support Core, but now I can't distribute my classes at all for any use in .NET Core.  Please fix urgently.

**Comment by fredericDelaporte** [comment]
> It is understood that NHibernate doesn't support Core

Since its [5.1 release](https://github.com/nhibernate/nhibernate-core/releases/tag/5.1.0) NHibernate supports .Net Core 2.0 and .Net Standard 2.0.

> Lacking .NET Standard support is a breaking problem for those of us that use NHibernate Attributes in classes of Models we include in NuGet packages for redistribution.

This is nothing new that adding a dependency to a library not supporting some frameworks causes your own library to not support them either. Use compilation directives in code and conditional package references to overcome this.

> Please fix urgently.

NHibernate is made by volunteers. We all have our own schedules and priorities.

**Comment by jpenniman** [comment]
@MSWCRB, there is a pull request in the works for this (#12). If you don't mind being bleeding edge and can't wait, there is a preview at...
https://www.myget.org/feed/milestonetg-public/package/nuget/NHibernate.Mapping.Attributes
...if you want to put it through the paces.
